### ISSUE TITLE
Can't find Inference.py

### ISSUE THREAD

**Issue by jspirit01** [MinkyuKim26/Prefix_AAC_ICASSP2023#2]
Thank you for sharing your codes. 

But, I can't find the `Inference.py`. 
Could you upload this file?

**Comment by MinkyuKim26** [comment]
Hi,
Sorry for providing the wrong information. I didn't upload the inference file. 
After finding this, I added the inference file to the repository and edited the readme for giving detailed information about using this file. 
If you have a question more, please ask me.
